name: test

on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            uses: actions/checkout@v2.3.4

          - name: Install dependencies
            run: |
              sudo apt-get update
              sudo apt install -y cpanminus build-essential libncurses5-dev libreadline-dev libssl-dev perl lua5.1 liblua5.1-0-dev

          - name: Install Test::Nginx
            run: |
              sudo cpanm --notest Test::Nginx > build.log 2>&1 || (cat build.log && exit 1)

          - name: Install openresty
            run: |
              wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
              sudo apt-get -y install software-properties-common
              sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"
              sudo apt-get update
              sudo apt-get install openresty
              git clone https://github.com/openresty/test-nginx.git test-nginx

          - name: Run tests
            run:
              make test
